Add deployment.environment support
signalfx/splunk-otel-dotnet pull request #106
Opened 2022-12-07 12:20 UTC by RassK

### What

Adds `deployment.environment` resource support.
In OTel spec this is advised but for SingalFX APM this is required.

https://signalfuse.atlassian.net/browse/APMI-3667

### Tests
TBD

2022-12-07 13:13 UTC, pellared requested changes
None of the distributions support `SIGNALFX_ENV`. It is legacy. I think we should close this PR.

2022-12-07 13:57 UTC, RassK commented
> None of the distributions support `SIGNALFX_ENV`. It is legacy. I think we should close this PR.

I agree, I would have used SPLUNK_ENV but this seems also not used. 
`OTEL_RESOURCE_ATTRIBUTES ` unfortunately is not suitable for global scope as more precise scope will overwrite the global env. To encounter it the more precise env needs to contain the content of global env, which means it is going to add multiple change (failure) points.

2022-12-07 13:59 UTC, theletterf commented
All our other distros use resource attributes to deal with this, AFAIK.

2022-12-07 14:22 UTC, theletterf commented
I can see the positive effect there. Wouldn't this have to be added to the GDI specs first though? Could changes be rolled out before that?

2022-12-07 17:36 UTC, RassK commented
Team meeting update: We will not bring any more `SINGALFX_*` vars.

2022-12-08 12:47 UTC, RassK commented
Linking spec issue here > https://github.com/open-telemetry/opentelemetry-specification/issues/3025

2023-01-19 11:16 UTC, closed without merging